### ISSUE TITLE
Leia uses a new Subtitle dialog and Aeonmq6-Leia doesn't expose it.

### ISSUE THREAD

**Issue by RedsGT** [Angelinas1/Aeonmq6-Leia#1]
Leia uses a new Subtitle dialog and Aeonmq6-Leia doesn't expose it.  This means there is no way to enable/disable/change the subtitles in the menu when using this skin.

**Comment by RedsGT** [comment]
Attempted fix for this issue - #2

**Comment by Angelinas1** [comment]
thanks!....merged
